name: camera_test
description: "Camera Test Application"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0
  device_info_plus: ^12.2.0
  camera: ^0.11.0
  path_provider: ^2.1.0
  path: ^1.9.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
