name: camera_test
description: "Camera Test Application"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0
  device_info_plus: ^12.2.0
  camera: ^0.11.0
  path_provider: ^2.1.0
  path: ^1.9.0
  image_picker: ^1.2.0
  share_plus: ^12.0.0
  vector_math: ^2.2.0
  video_thumbnail: ^0.5.0
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter-BlackItalic.ttf
          weight: 900
          style: italic